package:
  name: dateparser
  version: 0.7.4
source:
  sha256: fb5bfde4795fa4b179fe05c2c25b3981f785de26bec37e247dee1079c63d5689
  url: https://files.pythonhosted.org/packages/e2/da/c58ecd3b4183849b7373e6bbe140fdc0e0cc4640b960a1ddb5f550c2b283/dateparser-0.7.4.tar.gz
requirements:
  run:
  - convertdate
  - jdatetime
  - python-dateutil
  - pytz
  - regex
  - tzlocal
  - umalqurra
test:
  imports:
  - dateparser
